version: "3.5"
services:

  traefik:
    image: traefik:v2.0-alpine
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=admin@traefik.io"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  coder:
    image: codercom/code-server:2.1472-vsc1.38.1
    command: " /home/coder"
    ports:
      - 8080
    volumes:
      - ./:/home/coder
    labels:
      - traefik.http.routers.coder.rule=Host(`code.${DOMAIN}`)