version: "3.5"
services:
  traefik:
    image: traefik:v2.0-alpine
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  code:
    image: codercom/code-server:2.1472-vsc1.38.1
    command: " /home/coder"
    ports:
      - 8080
    volumes:
      - ./:/home/coder
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin:/usr/local/sbin
    labels:
      traefik.http.routers.code.rule: Host(`coder.${DOMAIN}`)
      traefik.http.routers.code2.rule: Host(`coder.${DOMAIN}`)
      traefik.http.routers.code2.entrypoints: websecure
      traefik.http.routers.code2.tls.certresolver: letsencrypt
